Ext.define("TaskManager.view.auth.Register", {
  extend: "Ext.window.Window",
  xtype: "register",
  reference: "register",

  requires: ["TaskManager.view.auth.AuthController", "Ext.form.Panel"],

  controller: "auth",
  bodyPadding: 10,
  title: "Registration Window",
  closable: false,
  autoShow: true,

  items: {
    xtype: "formpanel",
    reference: "registrationform",
    layout: "form",
    defaultButton: "register",
    defaultFocus: "email",
    items: [
      {
        xtype: "textfield",
        name: "email",
        fieldLabel: "Email",
        vtype: "email",
        allowBlank: false,
        label: "Email",
      },
      {
        xtype: "textfield",
        name: "phone",
        fieldLabel: "Phone",
        label: "Phone",
        allowBlank: false,
      },
      {
        xtype: "textfield",
        name: "firstName",
        fieldLabel: "First Name",
        allowBlank: false,
        label: "First Name",
      },
      {
        xtype: "textfield",
        name: "lastName",
        fieldLabel: "Last Name",
        allowBlank: false,
        label: "Last Name",
      },
      {
        xtype: "textfield",
        name: "street_address",
        fieldLabel: "Street Address",
        allowBlank: false,
        label: "Street Address",
      },
      {
        xtype: "textfield",
        name: "city",
        fieldLabel: "City",
        allowBlank: false,
        label: "City",
      },
      {
        xtype: "textfield",
        name: "state",
        fieldLabel: "State",
        allowBlank: false,
        label: "State",
      },
      {
        xtype: "textfield",
        name: "country",
        fieldLabel: "Country",
        allowBlank: false,
        label: "Country",
      },
      {
        xtype: "textfield",
        name: "postal_code",
        fieldLabel: "Postal Code",
        allowBlank: false,
        label: "Postal Code",
      },
      {
        xtype: "textfield",
        name: "password",
        inputType: "password",
        fieldLabel: "Password",
        allowBlank: false,
        label: "Password",
      },
      {
        xtype: "textfield",
        name: "confirmPassword",
        inputType: "password",
        fieldLabel: "Confirm Password",
        allowBlank: false,
        label: "Confirm Password",
      },
    ],
    buttons: [
      {
        text: "Return to Login",
        handler: "onBackToLoginClick",
      },
      {
        text: "Submit Registration",
        formBind: true,
        handler: "onRegisterSubmit",
        defaultButton: true,
      },
    ],
  },
});
